package pl.coco.perf;

import com.google.java.contract.Invariant;

@Invariant({
        "field != 0",
        "field != 1",
        "field != 2",
        "field != 3",
        "field != 4",
        "field != 5",
        "field != 6",
        "field != 7",
        "field != 8",
        "field != 9",
        "field != 10",
        "field != 11",
        "field != 12",
        "field != 13",
        "field != 14",
        "field != 15",
        "field != 16",
        "field != 17",
        "field != 18",
        "field != 19",
        "field != 20",
        "field != 21",
        "field != 22",
        "field != 23",
        "field != 24",
        "field != 25",
        "field != 26",
        "field != 27",
        "field != 28",
        "field != 29",
        "field != 30",
        "field != 31",
        "field != 32",
        "field != 33",
        "field != 34",
        "field != 35",
        "field != 36",
        "field != 37",
        "field != 38",
        "field != 39",
        "field != 40",
        "field != 41",
        "field != 42",
        "field != 43",
        "field != 44",
        "field != 45",
        "field != 46",
        "field != 47",
        "field != 48",
        "field != 49",
        "field != 50",
        "field != 51",
        "field != 52",
        "field != 53",
        "field != 54",
        "field != 55",
        "field != 56",
        "field != 57",
        "field != 58",
        "field != 59",
        "field != 60",
        "field != 61",
        "field != 62",
        "field != 63",
        "field != 64",
        "field != 65",
        "field != 66",
        "field != 67",
        "field != 68",
        "field != 69",
        "field != 70",
        "field != 71",
        "field != 72",
        "field != 73",
        "field != 74",
        "field != 75",
        "field != 76",
        "field != 77",
        "field != 78",
        "field != 79",
        "field != 80",
        "field != 81",
        "field != 82",
        "field != 83",
        "field != 84",
        "field != 85",
        "field != 86",
        "field != 87",
        "field != 88",
        "field != 89",
        "field != 90",
        "field != 91",
        "field != 92",
        "field != 93",
        "field != 94",
        "field != 95",
        "field != 96",
        "field != 97",
        "field != 98",
        "field != 99"
})
public class InvariantSubject100 {

    private int field = -1;

    public int target(int x) {
        if (field != Integer.MIN_VALUE) {
            field--;
        } else {
            field = 0;
        }
        return x;
    }
}
